---
- name: Provision
  hosts: all
  become: yes
  tasks:
    - name: upgrade os
      apt: upgrade=yes update_cache=yes cache_valid_time={{ 12 * 3600 }}

    - name: install os dependencies
      apt: name={{ packages }}
      vars:
        packages:
          - git
